---
# tasks file for gandalf

- name: Add tsuru repositories.
  apt_repository: repo="ppa:{{ tsuru_ppa }}" update_cache=yes

- name: Install packages.
  apt: update_cache=true name="{{ item }}"
  with_items:
    - curl
    - python-software-properties
    - "{% if gandalf_server_version is defined %}gandalf-server={{ gandalf_server_version }}{% else %}gandalf-server{% endif %}"
    - "{% if archive_server_version is defined %}archive-server={{ archive_server_version }}{% else %}archive-server{% endif %}"

- name: Create git hook directory.
  file: path={{ gandalf_git_template_dir }}/hooks state=directory owner=git group=git recurse=yes

- name: Install git hook.
  copy: src=pre-receive.archive-server dest={{ gandalf_git_template_dir }}/hooks/pre-receive owner=git group=git mode=0755

- name: Add archive server to bash profile.
  lineinfile: 'create=yes dest=/home/git/.bash_profile line="export ARCHIVE_SERVER_READ=http://{{gandalf_host_internal}}:3232 ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131"'
  notify:
    - restart gandalf
    - restart archive-server

- name: Add api endpoint to bash_profile
  lineinfile: 'create=yes dest=/home/git/.bash_profile line="export TSURU_HOST={{ tsuru_api_endpoint }}"'
  notify:
    - restart gandalf
    - restart archive-server

- name: Update gandalf.conf
  template: dest=/etc/gandalf.conf src=gandalf.conf.j2
  notify:
    - restart gandalf
    - restart archive-server

- name: Start gandalf
  service: name=gandalf-server state=started

- name: Update archive server conf.
  template: dest=/etc/default/archive-server src=archive-server.j2
  notify:
    - restart gandalf
    - restart archive-server

- name: Start archive-server
  service: name=archive-server state=started
